### ISSUE TITLE
Migrate commits from Mercurial to Git

### ISSUE THREAD

**Issue by fpoli** [viperproject/bitbucket-issue-migration#10]
For each non-merged pull request on bitbucket repository, pull the particular branch referenced in the pull request to a fresh branch (e.g. named `bitbucket-pr-123`) in the final repository.

Then, after migrating the repo we can open github pull requests for each non-merged bitbucket pull request, and github issues for merged pull requests.

For the migration: https://github.com/frej/fast-export

**Comment by ArquintL** [comment]
Steps:
1. `hg clone ssh://hg@ethbitbucket/viperproject/silver`
2. `cd silver`
3. `hg pull -r 69b4997 ssh://hg@ethbitbucket/arquintl/silver`
4. `hg update 69b4997` 
4. `hg branch bitbucket-pr-133`
5. `hg commit -m "creates branch bitbucket-pr-133"`
=> hg-fast-export succeeds, but the pulled commits appear on the master branch

With bookmarks:
1. `hg clone ssh://hg@ethbitbucket/viperproject/silver`
2. `cd silver`
3. `hg pull -r 69b4997 ssh://hg@ethbitbucket/arquintl/silver`
4. `hg update 69b4997` 
5. `hg bookmark bitbucket-pr-133`
=> does not work, because hg-fast-export reports `Error: repository has at least one unnamed head: hg r3778`, where r3778 is the latest commit on default that should become the latest commit on the master branch

Reverse order of branch creation and pull:
1. `hg clone ssh://hg@ethbitbucket/viperproject/silver`
2. `cd silver`
3. `hg branch bitbucket-pr-133`
4. `hg commit -m "creates branch bitbucket-pr-133"`
5. `hg pull -r 69b4997 ssh://hg@ethbitbucket/arquintl/silver`
6. `hg update 69b4997` 
=> creates a branch for the default branch, but all pulled commits are left unchanged

**Comment by ArquintL** [comment]
Newest approach:
1. `hg clone ssh://hg@ethbitbucket/viperproject/silver`
2. `cd silver`
3. `hg pull -r 69b4997 ssh://hg@ethbitbucket/arquintl/silver`

And then run [fix-repo](https://github.com/viperproject/fast-export/blob/master/fix-repo.py)

**Comment by ArquintL** [comment]
Open problem: translation of hg branches to git branches

**Comment by ArquintL** [comment]
A new branch is created for head commits that get pulled from e.g. `arquintl/silver`. The new branch is named `arquintl/silver/<branch_name>`, where `<branch_name>` corresponds to the branch on which the commit was on in the original repo (i.e. fork).
If this new branch name happens to be non-unique, the branch name is changed once more by appending `_x`, where `x` is an integer starting at 0.
See 0a287291c1f9be429f6938be08701a6a00913682

**Comment by fpoli** [comment]
Any clue about the error `RuntimeError: cmd hg --cwd viperproject/silver --encoding UTF-8 pull -r 5d3807586431 ssh://hg@ethbitbucket/viperproject/silver-attributes resulted in exit code 255 (abort: no suitable response from remote hg!
)`?

**Comment by ArquintL** [comment]
@fpoli please adapt `get_bitbucket_base_url()` in import-forks.py to return the ssh prefix you normally use to clone from Bitbucket, i.e. `ssh://hg@bitbucket.org/`

**Comment by fpoli** [comment]
> @fpoli please adapt `get_bitbucket_base_url()` in import-forks.py to return the ssh prefix you normally use to clone from Bitbucket, i.e. `ssh://hg@bitbucket.org/`

I see. Can I hardcode `ssh://hg@bitbucket.org/`, if it works also for you?
